services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tx-strategy_webapp_1
      APP_PORT: 2024
    
  webapp:
    image: nguyentuan1005/tx-strategy:latest
    pull_policy: always
    init: true
    ports:
      - 2024:2024
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:2024
